subdirs-$(CONFIG_ARCH_MSP430)+=msp430
subdirs-$(CONFIG_ARCH_AVR)+=avr
subdirs-$(CONFIG_ARCH_8051)+=8051
subdirs-y+=contrib


#TODO: Move these to generic, rework, nuke, cleanup
objects-$(CONFIG_LIB_SNPRINTF)+=snprintf.o
objects-$(CONFIG_LIB_NLIBSTUBS)+=newlib-dummies.o
objects-$(CONFIG_LIB_PRINTK)+=printk.o
objects-$(CONFIG_LIB_XMODEM)+=xmodem.o
objects-$(CONFIG_LIB_XPRINTF)+=xprintf.o
subdirs-$(CONFIG_LIB_URPC)+=urpc

subdirs-y+=ulc
