subdirs-$(CONFIG_ARCH_MSP430)+=msp430
subdirs-$(CONFIG_ARCH_AVR)+=avr
subdirs-$(CONFIG_ARCH_8051)+=8051
subdirs-y+=contrib
subdirs-$(CONFIG_LIB_URPC)+=urpc
subdirs-$(CONFIG_LIB_STLINKY)+=stlinky

objects-$(CONFIG_LIB_SNPRINTF)+=snprintf.o
objects-$(CONFIG_LIB_NLIBSTUBS)+=newlib-dummies.o
objects-$(CONFIG_LIB_PRINTK)+=printk.o
objects-$(CONFIG_LIB_INITCALL)+=initcall.o
objects-$(CONFIG_LIB_XMODEM)+=xmodem.o

subdirs-y+=ulc
