objects-$(CONFIG_LIB_SNPRINTF)+=snprintf.o
objects-$(CONFIG_LIB_NLDUMMY)+=newlib-dummies.o
objects-$(CONFIG_LIB_TMGR)+=tasks.o 
objects-$(CONFIG_LIB_PRINTK)+=printk.o
objects-$(CONFIG_LIB_XMODEM)+=xmodem.o
objects-$(CONFIG_LIB_XPRINTF)+=xprintf.o
