#directory i should grab the source from
SRCDIR?=.
#the directory i should dump .o to
OBJDIR?=.
#top level directory, where .config is
TOPDIR?=.
#antares directory where all the scripts are
ANTARES_DIR?=$(TOPDIR)/antares
#temporary dir for autogenerated stuff and other such shit
TMPDIR?=tmp

ANTARES_DIR:=$(abspath $(ANTARES_DIR))
TMPDIR:=$(abspath $(TMPDIR))
TOPDIR:=$(abspath $(TOPDIR))

Kbuild:=Kconfig
obj:=$(OBJDIR)/kconfig
src:=$(SRCDIR)/kconfig
Kconfig:=$(SRCDIR)/kcnf
KVersion:=./version.kcnf

PHONY+=deftarget deploy build collectinfo clean
MAKEFLAGS:=-r
#overrride with actual version information

IMAGENAME=$(call unquote,$(CONFIG_IMAGE_DIR))/$(call unquote,$(CONFIG_IMAGE_FILENAME))
CONFIG_MAKE_DEFTARGET := $(subst ",, $(CONFIG_MAKE_DEFTARGET))

-include $(TOPDIR)/.config
-include $(ANTARES_DIR)/.version

all: 
	$(Q)make $(CONFIG_MAKE_DEFTARGET)
	@echo "Default target $(CONFIG_MAKE_DEFTARGET) remade"


include $(ANTARES_DIR)/make/host.mk
include $(TMPDIR)/arch.mk
include $(ANTARES_DIR)/make/Makefile.lib
-include $(ANTARES_DIR)/src/arch/$(ARCH)/arch.mk

ifeq ($(CONFIG_TOOLCHAIN_GCC),y)
include $(ANTARES_DIR)/toolchains/gcc.mk
endif

include $(ANTARES_DIR)/make/Makefile.collect

-include src/arch/$(ARCH)/arch.mk

include $(ANTARES_DIR)/kconfig/kconfig.mk

.SUFFIXES:

export SRCDIR TMPDIR IMAGENAME ARCH TOPDIR ANTARES_DIR

#FixMe: Properly clean the project tree
clean: 
# 	$(MAKE) OBJDIR=$(SRCDIR)/src SRCDIR=$(SRCDIR) TMPDIR=$(TMPDIR) -f make/Makefile.build -r clean
	$(Q)find . -iname *.o| while read line; do rm "$$line"; done
	$(Q)rm -f tmp/*


mrproper: clean kconfig-clean 
	$(Q)-rm -Rfv $(TMPDIR)
	$(Q)-rm -Rfv $(TOPDIR)/kconfig
	$(Q)-rm -Rfv $(TOPDIR)/include
	@echo "Мистер пропёр - веселей, в сырцах чисто в 3 раза быстрей!"

# build: collectinfo silentoldconfig collectinfo $(BUILD_PREREQS) 
# 	$(Q)$(MAKE) OBJDIR=$(SRCDIR)/src SRCDIR=$(SRCDIR) TMPDIR=$(TMPDIR) -f make/Makefile.build -r build

build: collectinfo silentoldconfig collectinfo $(BUILDGOALS)

deploy: build
	$(Q)$(MAKE) -f $(SRCDIR)/make/Makefile.deploy $(call unquote,$(CONFIG_DEPLOY_DEFTARGET))
	@echo "Your Antares firmware is now deployed"

deploy-%: build
	$(Q)$(MAKE) -f $(SRCDIR)/make/Makefile.deploy $*
	@echo "Your Antares firmware is now deployed"
	$(Q)$(MAKE) -f $(SRCDIR)/make/Makefile.deploy post

deploy-help:
	make -f make/Makefile.deploy help

.PHONY: $(PHONY)
