subdirs-y +=startup extra
subdirs-$(CONFIG_STM32F1X) += library-f1x
subdirs-$(CONFIG_STM32F4X) += library-f4x
subdirs-$(CONFIG_STM32F1X_USB) += usb-f1x

# Antares startup code 
objects-$(CONFIG_ANTARES_STARTUP)+= dummy.o
