# Mandatory objects for LUFA stack 
objects-y += USBController_AVR8.o  USBInterrupt_AVR8.o 

# USB Device sources
objects-$(CONFIG_LIB_LUFA_DEVICE) += Device_AVR8.o Endpoint_AVR8.o EndpointStream_AVR8.o
# USB Host sources
objects-$(CONFIG_LIB_LUFA_HOST) += Host_AVR8.o  Pipe_AVR8.o  PipeStream_AVR8.o  
