# Automatically generated. Not recommended to edit
ifeq ($(CONFIG_ARM_MARCH_CORTEX-M0),y)
ARM_MARCH=cortex-m0
endif
ifeq ($(CONFIG_ARM_MARCH_CORTEX-M1),y)
ARM_MARCH=cortex-m1
endif
ifeq ($(CONFIG_ARM_MARCH_CORTEX-M3),y)
ARM_MARCH=cortex-m3
endif
ifeq ($(CONFIG_ARM_MARCH_CORTEX-M4),y)
ARM_MARCH=cortex-m4
endif
ifeq ($(CONFIG_ARM_MARCH_CORTEX-R4F),y)
ARM_MARCH=cortex-r4f
endif
ifeq ($(CONFIG_ARM_MARCH_CORTEX-R4),y)
ARM_MARCH=cortex-r4
endif
ifeq ($(CONFIG_ARM_MARCH_CORTEX-A9),y)
ARM_MARCH=cortex-a9
endif
ifeq ($(CONFIG_ARM_MARCH_CORTEX-A8),y)
ARM_MARCH=cortex-a8
endif
ifeq ($(CONFIG_ARM_MARCH_CORTEX-A5),y)
ARM_MARCH=cortex-a5
endif
ifeq ($(CONFIG_ARM_MARCH_ARM1156T2F-S),y)
ARM_MARCH=arm1156t2f-s
endif
ifeq ($(CONFIG_ARM_MARCH_ARM1156T2-S),y)
ARM_MARCH=arm1156t2-s
endif
ifeq ($(CONFIG_ARM_MARCH_MPCORE),y)
ARM_MARCH=mpcore
endif
ifeq ($(CONFIG_ARM_MARCH_MPCORENOVFP),y)
ARM_MARCH=mpcorenovfp
endif
ifeq ($(CONFIG_ARM_MARCH_ARM1176JZF-S),y)
ARM_MARCH=arm1176jzf-s
endif
ifeq ($(CONFIG_ARM_MARCH_ARM1176JZ-S),y)
ARM_MARCH=arm1176jz-s
endif
ifeq ($(CONFIG_ARM_MARCH_ARM1136JF-S),y)
ARM_MARCH=arm1136jf-s
endif
ifeq ($(CONFIG_ARM_MARCH_ARM1136J-S),y)
ARM_MARCH=arm1136j-s
endif
ifeq ($(CONFIG_ARM_MARCH_ARM1026EJ-S),y)
ARM_MARCH=arm1026ej-s
endif
ifeq ($(CONFIG_ARM_MARCH_ARM926EJ-S),y)
ARM_MARCH=arm926ej-s
endif
ifeq ($(CONFIG_ARM_MARCH_IWMMXT2),y)
ARM_MARCH=iwmmxt2
endif
ifeq ($(CONFIG_ARM_MARCH_IWMMXT),y)
ARM_MARCH=iwmmxt
endif
ifeq ($(CONFIG_ARM_MARCH_XSCALE),y)
ARM_MARCH=xscale
endif
ifeq ($(CONFIG_ARM_MARCH_ARM1022E),y)
ARM_MARCH=arm1022e
endif
ifeq ($(CONFIG_ARM_MARCH_ARM1020E),y)
ARM_MARCH=arm1020e
endif
ifeq ($(CONFIG_ARM_MARCH_ARM10E),y)
ARM_MARCH=arm10e
endif
ifeq ($(CONFIG_ARM_MARCH_ARM968E-S),y)
ARM_MARCH=arm968e-s
endif
ifeq ($(CONFIG_ARM_MARCH_ARM966E-S),y)
ARM_MARCH=arm966e-s
endif
ifeq ($(CONFIG_ARM_MARCH_ARM946E-S),y)
ARM_MARCH=arm946e-s
endif
ifeq ($(CONFIG_ARM_MARCH_ARM9E),y)
ARM_MARCH=arm9e
endif
ifeq ($(CONFIG_ARM_MARCH_ARM1020T),y)
ARM_MARCH=arm1020t
endif
ifeq ($(CONFIG_ARM_MARCH_ARM10TDMI),y)
ARM_MARCH=arm10tdmi
endif
ifeq ($(CONFIG_ARM_MARCH_EP9312),y)
ARM_MARCH=ep9312
endif
ifeq ($(CONFIG_ARM_MARCH_ARM940T),y)
ARM_MARCH=arm940t
endif
ifeq ($(CONFIG_ARM_MARCH_ARM922T),y)
ARM_MARCH=arm922t
endif
ifeq ($(CONFIG_ARM_MARCH_ARM920T),y)
ARM_MARCH=arm920t
endif
ifeq ($(CONFIG_ARM_MARCH_ARM920),y)
ARM_MARCH=arm920
endif
ifeq ($(CONFIG_ARM_MARCH_ARM9TDMI),y)
ARM_MARCH=arm9tdmi
endif
ifeq ($(CONFIG_ARM_MARCH_ARM9),y)
ARM_MARCH=arm9
endif
ifeq ($(CONFIG_ARM_MARCH_ARM740T),y)
ARM_MARCH=arm740t
endif
ifeq ($(CONFIG_ARM_MARCH_ARM720T),y)
ARM_MARCH=arm720t
endif
ifeq ($(CONFIG_ARM_MARCH_ARM710T),y)
ARM_MARCH=arm710t
endif
ifeq ($(CONFIG_ARM_MARCH_ARM7TDMI-S),y)
ARM_MARCH=arm7tdmi-s
endif
ifeq ($(CONFIG_ARM_MARCH_ARM7TDMI),y)
ARM_MARCH=arm7tdmi
endif
ifeq ($(CONFIG_ARM_MARCH_STRONGARM1110),y)
ARM_MARCH=strongarm1110
endif
ifeq ($(CONFIG_ARM_MARCH_STRONGARM1100),y)
ARM_MARCH=strongarm1100
endif
ifeq ($(CONFIG_ARM_MARCH_STRONGARM110),y)
ARM_MARCH=strongarm110
endif
ifeq ($(CONFIG_ARM_MARCH_STRONGARM),y)
ARM_MARCH=strongarm
endif
ifeq ($(CONFIG_ARM_MARCH_ARM810),y)
ARM_MARCH=arm810
endif
ifeq ($(CONFIG_ARM_MARCH_ARM8),y)
ARM_MARCH=arm8
endif
ifeq ($(CONFIG_ARM_MARCH_ARM7DMI),y)
ARM_MARCH=arm7dmi
endif
ifeq ($(CONFIG_ARM_MARCH_ARM7DM),y)
ARM_MARCH=arm7dm
endif
ifeq ($(CONFIG_ARM_MARCH_ARM7M),y)
ARM_MARCH=arm7m
endif
ifeq ($(CONFIG_ARM_MARCH_ARM7500FE),y)
ARM_MARCH=arm7500fe
endif
ifeq ($(CONFIG_ARM_MARCH_ARM7500),y)
ARM_MARCH=arm7500
endif
ifeq ($(CONFIG_ARM_MARCH_ARM7100),y)
ARM_MARCH=arm7100
endif
ifeq ($(CONFIG_ARM_MARCH_ARM710C),y)
ARM_MARCH=arm710c
endif
ifeq ($(CONFIG_ARM_MARCH_ARM720),y)
ARM_MARCH=arm720
endif
ifeq ($(CONFIG_ARM_MARCH_ARM710),y)
ARM_MARCH=arm710
endif
ifeq ($(CONFIG_ARM_MARCH_ARM700I),y)
ARM_MARCH=arm700i
endif
ifeq ($(CONFIG_ARM_MARCH_ARM700),y)
ARM_MARCH=arm700
endif
ifeq ($(CONFIG_ARM_MARCH_ARM70),y)
ARM_MARCH=arm70
endif
ifeq ($(CONFIG_ARM_MARCH_ARM7DI),y)
ARM_MARCH=arm7di
endif
ifeq ($(CONFIG_ARM_MARCH_ARM7D),y)
ARM_MARCH=arm7d
endif
ifeq ($(CONFIG_ARM_MARCH_ARM7),y)
ARM_MARCH=arm7
endif
ifeq ($(CONFIG_ARM_MARCH_ARM620),y)
ARM_MARCH=arm620
endif
ifeq ($(CONFIG_ARM_MARCH_ARM610),y)
ARM_MARCH=arm610
endif
ifeq ($(CONFIG_ARM_MARCH_ARM600),y)
ARM_MARCH=arm600
endif
ifeq ($(CONFIG_ARM_MARCH_ARM60),y)
ARM_MARCH=arm60
endif
ifeq ($(CONFIG_ARM_MARCH_ARM6),y)
ARM_MARCH=arm6
endif
ifeq ($(CONFIG_ARM_MARCH_ARM3),y)
ARM_MARCH=arm3
endif
ifeq ($(CONFIG_ARM_MARCH_ARM250),y)
ARM_MARCH=arm250
endif
ifeq ($(CONFIG_ARM_MARCH_ARM2),y)
ARM_MARCH=arm2
endif
