objects-$(CONFIG_CONTRIB_CRUMBO_UART)+=uart.o
objects-$(CONFIG_CONTRIB_CRUMBO_DEBUG)+=debug.o
objects-$(CONFIG_CONTRIB_CRUMBO_MEXTRA)+=manip_extra.o
objects-$(CONFIG_CONTRIB_CRUMBO_ADC)+=adc.o
objects-$(CONFIG_CONTRIB_CRUMBO_ENCODER)+=encoder.o
objects-$(CONFIG_CONTRIB_CRUMBO_DEBUG)+=debug.o
objects-$(CONFIG_CONTRIB_CRUMBO_MANIP)+=manipulator.o
objects-$(CONFIG_CONTRIB_CRUMBO_CHASSIS)+=chassis.o
objects-$(CONFIG_CONTRIB_CRUMBO_START)+=start_cond.o
objects-$(CONFIG_CONTRIB_CRUMBO_SYSTICK)+=systick.o

$(info Crumbo source code is deprecated! Do not rely on any APIs)
