#!/bin/bash

COLOR_BANNER="\e[33;1m"
COLOR_BAR="\e[32;1m"
COLOR_RESET="\e[0m"
COLOR_ERROR="\e[31;5m"


COLS=`tput cols`
BANNER=$1

if [ "$2" == "" ]; then
let VALUE=0
else
let VALUE=$2
fi

if [ "$3" == "" ]; then
let MAX=1
else
let MAX=$3
fi

if [ $MAX -lt $VALUE ]; then
    echo -e "!!!WARNING!!! $COLOR_ERROR$BANNER overflow$COLOR_RESET !!!WARNING!!!"
    echo -e "You want $COLOR_BANNER$VALUE$COLOR_RESET bytes, but device has only $COLOR_BANNER$MAX$COLOR_RESET"
    exit 1; #Make the makfiles produce an error
fi

PRCNT=$((VALUE*100/MAX))
PRCNT="] $PRCNT% used"

BANNER="$COLOR_BANNER$BANNER$COLOR_RESET: $VALUE/$MAX bytes"

COLS=$((COLS-60))
FCOLS=$((VALUE*COLS/MAX))

echo -ne "$BANNER \r\t\t\t\t\t[$COLOR_BAR"

for ((i=0; i<$FCOLS; i++)); do
    echo -n "#"
done
echo -ne "$COLOR_RESET"

COLS=$((COLS-FCOLS))
for ((i=0; i<$COLS; i++)); do
    echo -n "-"
done

echo -e "$PRCNT"
