#!/bin/bash
read_builtin()
{
	local DIR="`dirname $1`"
for line in `cat $1`; do 
	if [ "`basename $line`" == "built-in.${O}" ]; then 
		read_builtin "$DIR/$line"; 
	else
		echo "$DIR/$line";
	fi; 
done
}
read_builtin "$1"
