#!/bin/bash
# This helper script parses the avrdude config file
# And grabs useful infos about the devices avaliable
# Yarr!

parse_key_val()
{
KEY=`echo $1|cut -d"=" -f1`
KEY=${KEY/ /}
VAL=`echo $1|cut -d"=" -f2`
VAL=${VAL/ /}
VAL=${VAL/\"/}
VAL=${VAL/\";/}
}

parse_line()
{
KEY=`echo $1|cut -d" " -f1`
KEY=${KEY/ /}
VAL=`echo $1|cut -d" " -f2`
VAL=${VAL/ /}
VAL=${VAL/\"/}
VAL=${VAL/\";/}
}



STATE=0
cat /etc/avrdude.conf |grep -E "part|size|id|desc|memory"|while read line; do
#grep until the first part
if [ "$line" == "part" ]; then
  STATE=1
fi
  parse_key_val "$line"
  if [ "$KEY" == "id" ]; then
  MCU_ID=$VAL
  fi
  if [ "$KEY" == "id" ]; then
  MCU_ID=$VAL
  fi

parse_line "$line"

if [ "$KEY" == "memory" ]; then
MEM=$VAL
fi
if [ "$KEY" == "size" ]; then
${MEM}_SIZE=$VAL
echo $
done
