#!/bin/bash
# This script extracts linkage ordering rules
# In the form usable by make. 
SRC=$1
BNAME=`dirname $1`/`basename $1 .c`
#Yep, I don't know sed very good, nor have time to look up. So 
#let it be a dirty hack. Patches welcome

MVAR=`echo "$BNAME"| sed 's/\//_/g'| sed 's/\./_/g'`
parse_rule()
{
  module=$2
  shift 
  shift
  shift 
  echo "$MVAR=markers/$module"
  echo "\$(BUILD_DIR)/markers/$module: \$(addprefix markers/,$*)"
  echo "	touch \$(BUILD_DIR)markers/$module"
  
}

cat $1|grep ANTARES_LINK_RULE|while read line; do rule=`echo $line|cut -d'"' -f2`; parse_rule $rule; done