#!/bin/bash

sizeparse() 
{
    S=`echo $2|cut -d"K" -f 1`
    S=$((S*1024))
    printf "%s=0x%x\n" $1 $S
}

densityparse()
{
    $ANTARES_DIR/scripts/stm32chipid $*
}

STR=`cat`
RAM=`echo "$STR" | awk '/bootloader/ {print $3}'`
FLASH=`echo "$STR" | awk '/Flash/ {print $3}'`
DENSITY=`echo "$STR" | awk '/Device ID/ {print $4}'`

echo "#AUTOMATICALLY PATCHED INFO FROM STM32FLASH"
sizeparse CONFIG_STM32_RAM_LEN $RAM
sizeparse CONFIG_STM32_FLASH_LEN $FLASH
densityparse $DENSITY

