#Coloring support
t_blk=\e[0;30m
t_red=\e[0;31m
t_grn=\e[0;32m
t_ylw=\e[0;33m
t_blu=\e[0;34m
t_pur=\e[0;35m
t_cyn=\e[0;36m
t_wht=\e[0;37m

tb_blk=\e[1;30m
tb_red=\e[1;31m
tb_grn=\e[1;32m
tb_ylw=\e[1;33m
tb_blu=\e[1;34m
tb_pur=\e[1;35m
tb_cyn=\e[1;36m
tb_wht=\e[1;37m

tu_blk=\e[4;30m
tu_red=\e[4;31m
tu_grn=\e[4;32m
tu_ylw=\e[4;33m
tu_blu=\e[4;34m
tu_pur=\e[4;35m
tu_cyn=\e[4;36m
tu_wht=\e[4;37m

bg_blk=\e[40m
bg_red=\e[41m
bg_grn=\e[42m
bg_ylw=\e[43m
bg_blu=\e[44m
bg_pur=\e[45m
bg_cyn=\e[46m
bg_wht=\e[47m
col_rst=\e[0m

unquote=$(subst ",,$(1))

colorize=@echo -ne '$(1)'
IMAGES_DIR=images/