-include .config
include make/Makefile.lib
include deploy/Makefile

all: $(call unquote, $(CONFIG_DEPLOY_DEFAULT))
	echo 1

help:	
	@echo "Current firmware deployment methods are avaliable:"
	@echo $(deploy_help)
	@echo "Running 'make deploy' will invoke this methods: $(CONFIG_DEPLOY_DEFTARGET)"
	@echo "You may setup additional deployment scenarios in menuconfig"
	
.PHONY: $(PHONY)