#Core stuff
objects-$(CONFIG_LIB_EARLYCON)+=earlyprintk.o

#Earlycon drivers
objects-$(CONFIG_LIB_EARLYCON_AVRSERIAL)+=earlycon-avrserial.o
objects-$(CONFIG_LIB_EARLYCON_STCUART)+=earlycon-stc.o
objects-$(CONFIG_LIB_EARLYCON_NATIVE)+=earlycon-host.o
objects-$(CONFIG_LIB_EARLYCON_STLINKY)+=earlycon-stlinky.o
objects-$(CONFIG_LIB_EARLYCON_MSP430SOFTSERIAL)+=earlycon-msp430softserial.o

#Libc/printk glue
objects-$(CONFIG_LIB_EARLYCON_GLUE_AVR)+=glue-avrlibc.o
objects-$(CONFIG_LIB_EARLYCON_GLUE_SDCC)+=glue-sdcc.o
objects-$(CONFIG_LIB_EARLYCON_GLUE_MSP430)+=glue-msp430.o
objects-$(CONFIG_LIB_EARLYCON_GLUE_NEWLIB)+=glue-newlib.o



