aliens+="\nlibmaple - C code library for STM32 by leaflabs"
targets-y+=libmaple

libmaple_cflags=
libmaple_asflags=
libmaple_ldflags=

#Get's the actual source
define libmaple_download
	git clone https://github.com/leaflabs/libmaple.git src/alien/libmaple/source
endef

define libmaple_update
	cd src/alien/libmaple/source && git pull
endef


#prepares the source
define libmaple_prepare

endef

#custom build commands (e.g. make, if 
define libmaple_build

endef
	
