#!/bin/bash
# Grab in xls at st.com
# Actually, there's a buggy and broken html there. (SURPRIZE?)
# We use tidy on it, then plain grep|cut do the job... hehe
# This script assumes that the html is tidy'd already

source `dirname $0`/../../common

#usage: parse_productlist file

get_mcu_list()
{
cat $1|while read line; do
echo $line|cut -d"," -f 1|tr -d [\"]
done
}

gen_stm32_mk()
{
cat $1|while read line; do
if [ "$line" != "" ]; then
MCU=`echo $line|cut -d"," -f 1|tr -d [\"]`
SPEED=`echo $line|cut -d"," -f 4|tr -d [\"]`000000
FLASH_SZ=`echo $line|cut -d"," -f 5|tr -d [\"]`
RAM_SZ=`echo $line|cut -d"," -f 6|tr -d [\"]`
echo "ifeq (\$(CONFIG_$2_$MCU),y)"
echo "MCU=$MCU"
echo "MAX_SPEED=$SPEED"
echo "RAM_SIZE=`echo $RAM_SZ*1024|bc`"
echo "FLASH_SIZE=`echo $FLASH_SZ*1024|bc`"   
echo "endif" 
fi
done
}

echo "#Autogenerated, as well. Do not edit" > stm32f_list.kcnf
get_mcu_list $1|gen_kcnf MCU >> stm32f_list.kcnf

echo "Generating mk file"
gen_stm32_mk $1 MCU >> stm32f_list.mk
echo "Done"

#cat $1|while read line; do
#MCU=`echo $line|cut -d"," -f 1|tr -d [\"]`
#SPEED=`echo $line|cut -d"," -f 4|tr -d [\"]`000000
#FLASH_SZ=`echo $line|cut -d"," -f 5|tr -d [\"]`000000
#RAM_SZ=`echo $line|cut -d"," -f 6|tr -d [\"]`
#done